---
- name: Basic Web Server Setup
  hosts: servers
  gather_facts: False
  become: yes

  tasks:
    # Ensure SSH connection is available
    - name: Ensure SSH connection is available
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ ansible_host | default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        become: no

- name: Install Docker and Docker Compose
  hosts: servers
  become: yes
  vars_files:
    - ansible-vars.yaml

  tasks:
    # Update apt cache manually
    - name: Update apt cache manually
      apt:
        update_cache: yes
        cache_valid_time: "{{ cache_time }}"

    # Install Docker
    - name: Install Docker
      apt:
        name: "{{ docker_package_name }}"
        update_cache: yes
        state: present

    # Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    # Ensure Docker service is started
    - name: Ensure Docker service is started
      systemd:
        name: "{{ docker_service_name }}"
        state: started
        enabled: yes

    # Check Docker version
    - name: Check Docker version
      command: docker --version
      register: docker_version_output

    # Display Docker version
    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version_output.stdout }}"

    # Check Docker Compose version
    - name: Check Docker Compose version
      command: docker-compose --version
      register: docker_compose_version_output

    # Display Docker Compose version
    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version_output.stdout }}"

    # Add ubuntu user to docker group
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # Reconnect to server session
    - name: Reconnect to server session
      meta: reset_connection

- name: Install AWS CLI on EC2 Instances
  hosts: servers
  become: yes
  tasks:
    # Ensure curl is installed
    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    # Ensure unzip is installed
    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present

    # Check if AWS CLI is installed
    - name: Check if AWS CLI is installed
      command: "aws --version"
      register: aws_cli_check
      ignore_errors: true

    # Download AWS CLI installation script using curl
    - name: Download AWS CLI installation script using curl
      command: curl -o /tmp/awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      when: aws_cli_check.failed

    # Unzip AWS CLI installation package
    - name: Unzip AWS CLI installation package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"
        remote_src: yes
      when: aws_cli_check.failed

    # Run AWS CLI installer
    - name: Run AWS CLI installer
      command: "/tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin --update"
      when: aws_cli_check.failed

    # Verify AWS CLI installation
    - name: Verify AWS CLI installation
      command: "aws --version"
      register: aws_cli_version

    # Display AWS CLI version
    - name: Display AWS CLI version
      debug:
        msg: "AWS CLI version: {{ aws_cli_version.stdout }}"

- name: Pull Docker images for frontend and backend from ECR
  hosts: servers
  become: yes
  vars_files:
    - ansible-vars.yaml

  tasks:
    # Ensure AWS CLI is installed and in PATH
    - name: Check if AWS CLI is installed and in PATH
      command: aws --version
      register: aws_version_check
      ignore_errors: true

    - name: Display AWS CLI version or error
      debug:
        msg: "{{ aws_version_check.stdout if aws_version_check.stdout else aws_version_check.stderr }}"

    # Set AWS CLI path in environment
    - name: Set AWS CLI path in environment
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      command: "aws --version"

    # Retrieve the ECR login password using AWS CLI
    - name: Get ECR login password
      command: "aws ecr get-login-password --region us-east-1"
      register: ecr_login_password
      changed_when: false

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      docker_login:
        registry_url: "{{ ecr_url }}"
        username: AWS
        password: "{{ ecr_login_password.stdout }}"
        reauthorize: yes

    # Pull frontend Docker image from ECR
    - name: Pull frontend Docker image from ECR
      docker_image:
        name: "{{ ecr_url }}/{{ ecr_repository }}"
        tag: "{{ frontend_image_tag }}"
        source: pull

    # Pull backend Docker image from ECR
    - name: Pull backend Docker image from ECR
      docker_image:
        name: "{{ ecr_url }}/{{ ecr_repository }}"
        tag: "{{ backend_image_tag }}"
        source: pull

    # Display Docker images on the host
    - name: Display Docker images on the host
      command: docker images
      register: docker_images_output

    # Show Docker images
    - name: Show Docker images
      debug:
        msg: "{{ docker_images_output.stdout }}"

- name: Start Docker containers
  hosts: servers
  become: yes
  vars_files:
    - ansible-vars.yaml

  tasks:
    - name: Create Docker Network
      docker_network:
        name: "{{ docker_network_name }}"
        state: present

    - name: Copy Docker Compose file to the EC2 instance
      copy:
        src: "{{ compose_local_path }}"
        dest: "{{ compose_remote_path }}"

    - name: Start Docker containers from Docker Compose
      docker_compose:
        project_src: "{{ project_src_path }}"
        state: present

    - name: Run makemigrations inside backend container
      command: docker exec {{ backend_container_name }} python manage.py makemigrations

    - name: Run migrate inside backend container
      command: docker exec {{ backend_container_name }} python manage.py migrate

    - name: Create superuser inside backend container
      command: docker exec {{ backend_container_name }} python manage.py shell -c "from django.contrib.auth import get_user_model;User = get_user_model();User.objects.filter(username='{{ superuser_username }}').exists() or User.objects.create_superuser('{{ superuser_username }}', '{{ superuser_email }}', '{{ superuser_password }}')"
